on: [push]

jobs:
  check_compile_job:
    runs-on: ubuntu-latest
    name: testing check compiled
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: check compiled - but for laughs
        uses: sonarsource/gh-action-lt-backlog/CheckCompiledCommited@feature/check-compiled-commited
        with:
          build-command: 'echo hi'
